### ISSUE TITLE
Do wee need cuda 9.2 to enable chamfer distance？

### ISSUE THREAD

**Issue by Colin97** [Tong-ZHAO/Pixel2Mesh-Pytorch#1]
My cuda is 9.0 and there is an illegal memory access when using chamfer distance， so I was wondering whether cuda 9.2 is necessary...

**Comment by Tong-ZHAO** [comment]
When I was using cuda 9.0 at the beginning, I got a similar error.  And it disappeared after I updated my cuda. I recommend you to try it ,otherwise we may find other solutions.
