### ISSUE TITLE
normal

### ISSUE THREAD

**Issue by zjxyz** [Tong-ZHAO/Pixel2Mesh-Pytorch#10]
hello,
I have a question.
Inside the code，（img, pts, normal, _, _ = data).
But 'normal' isn't used in the back.

**Comment by Tong-ZHAO** [comment]
Hi, in the original paper the authors proposed a normal loss which is not implemented in my code. We intended to do it but we didn't have enough time. >.<

**Comment by zjxyz** [comment]
Thank you for your reply.  >.<
