### ISSUE TITLE
chamfer

### ISSUE THREAD

**Issue by zjxyz** [Tong-ZHAO/Pixel2Mesh-Pytorch#11]
hi, when I run python train.py, I get a wrong.
 file "model/chamfer/dist_chamfer.py", line 31, in forward
      chamfer.forward(xyz1,xyz2,dist1,dist2,idx1,idx2)
RuntimeError: expected scalar type Float but found Double(data<float> at /usr/local/python3.5/dist-packages/torch/include/ATen/core/TensorMethods.h:1386)

Thank you in advance!

**Comment by Tong-ZHAO** [comment]
Hi, I would like to know if you changed the code. If so, I suggest you to change the type of your input to torch.float32. Since in pytorch torch.float64 means Double and torch.float32 means Float.

**Comment by zjxyz** [comment]
I didn't find the code to generate the training data, so I changed the code to generate the training data. Now I change the input data to float32, which solves the problem.
Thank you ! =v=
