### ISSUE TITLE
Some questions about the arch of VGG16

### ISSUE THREAD

**Issue by hideonInternet** [Tong-ZHAO/Pixel2Mesh-Pytorch#2]
Hi, it is an awesome job! 
But there are still some questions for me about the arch of VGG. I have seen the code provided by the author, the arch of the "VGG net" is same as yours. But I found that is different from the original arch of the VGG16,e.g. it doesn't have a maxpool layer ( i mean the encode part). In the [paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Nanyang_Wang_Pixel2Mesh_Generating_3D_ECCV_2018_paper.pdf), the author doesn't make it clear, could you help me with that? :) Thanks in advance!

**Comment by Tong-ZHAO** [comment]
Hi, thanks for your appreciation. 
I do think that the choice of the encoder architecture does not have a big influence on the final result. In my test it converges quickly. I respected the author's choice in my implementation but you can easily change it ^.^ A conv layer with stride=2 replaces max-pooling.

**Comment by hideonInternet** [comment]
Thanks a lot!
