### ISSUE TITLE
   Based on what to add vertices

### ISSUE THREAD

**Issue by tingfengwanxiao** [Tong-ZHAO/Pixel2Mesh-Pytorch#4]
Hello, in the original paper, the ellipsoid is deformed by three deformed blocks, but how to increase the number of ellipsoid vertices? I found that he did not add vertices to every triangle. What is the basis for that?thank you

**Comment by Tong-ZHAO** [comment]
Hello. The mesh is deformed in each unpooling layer. To add vertices, we simply add the midpoints of all edges and we take the averages of two endpoints as their features. To add edges, we connect all added vertices in each triangle.

**Comment by tingfengwanxiao** [comment]
ok,I understand,thank you
