### ISSUE TITLE
add a deformation block

### ISSUE THREAD

**Issue by tingfengwanxiao** [Tong-ZHAO/Pixel2Mesh-Pytorch#5]
Have you ever tried to add another deformation block to four to show better details? If I want to add to four deformation blocks, how should I change the demo?

**Comment by Tong-ZHAO** [comment]
Hi, it is possible to add deformation blocks but you need to modify the file: 'data/info_ellipsoid.dat'.  To better understand its data structure, you can refer to the function 'read_init_mesh' in 'utils'. Personally I have not yet tried to understand how they create the file. >.< Once you have a new info_ellipsoid.dat, some modifications of models and losses should be modified (but trivial).

**Comment by tingfengwanxiao** [comment]
ok,thanks for your answer.
