### ISSUE TITLE
import chamfer

### ISSUE THREAD

**Issue by zjxyz** [Tong-ZHAO/Pixel2Mesh-Pytorch#6]
hello,
os:ubuntu 16.04
Pytorch version:1.0
python version:3.5
cuda version:9.2

when I import chamfer, I get a error.
ImportError:/usr/loacal/../charmfer.cpython-35m-x86-linux-gnu.so:  undefined symbol: _ZN2at5ErrorC1ES_14SourceLocationERKSs

**Comment by Tong-ZHAO** [comment]
Hi, it seems that the cuda doesn't go with the system. I suggest you to try different versions. Personally I use python 3.6 + Pytorch 1.0 + cuda 9.2 + ubuntu 16.04.

**Comment by zjxyz** [comment]
It should be an environmental problem, but I don't know how to solve it.
Thank you for your reply！
