### ISSUE TITLE
Failed to install chamfer

### ISSUE THREAD

**Issue by vbcpascal** [Tong-ZHAO/Pixel2Mesh-Pytorch#8]
Hi, when I tried to install chamfer, I got this error:
```
/usr/local/cuda/include/crt/host_config.h:129:2: 错误：#error -- unsupported GNU version! gcc versions later than 8 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
```
using Fedora 30, CUDA 10.0, python 3.7
What should I do now, thanks.

**Comment by Tong-ZHAO** [comment]
Hi, since your cuda is incompatible with the gcc version, you can refer to this discussion: https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version
Good luck ^.^

**Comment by vbcpascal** [comment]
It works, thanks.
