### ISSUE TITLE
data

### ISSUE THREAD

**Issue by zjxyz** [Tong-ZHAO/Pixel2Mesh-Pytorch#9]
hi，
I want to know the theory of converting cloud data into two-dimensional images.
Thanks in advance!

**Comment by Tong-ZHAO** [comment]
Hi, if I have understood correctly, you want to know how to project the points onto the image. In this project,  once we know the camera position (which is fixed), we can calculate directly its coordinate on a 2d plane. Then we find the four corners around its coordinate and extract their VGG features. The final feature is the bilinear interpolation of these 4 vectors.

**Comment by zjxyz** [comment]
Thank you for your reply！
There is a misunderstanding in my original statement. What I want to know is how to process the training set and how to transform the 3-D data set of shapenet into 2-D image. I want to understand the theory of code in this area.
